// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMc837Ly9kCTbp81A6c_DOMbzAx75mX8',
    appId: '1:808393767406:web:746e62553c155bedd6f6ff',
    messagingSenderId: '808393767406',
    projectId: 'login-7f7e4',
    authDomain: 'login-7f7e4.firebaseapp.com',
    databaseURL: 'https://login-7f7e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-7f7e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENlvEI5_YY8DHGeupk1aJjbonlmBvYrM',
    appId: '1:808393767406:android:5305206220941868d6f6ff',
    messagingSenderId: '808393767406',
    projectId: 'login-7f7e4',
    databaseURL: 'https://login-7f7e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-7f7e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4a9NXP7VE0RzjQzmPv9SL8kSTNFbYAmA',
    appId: '1:808393767406:ios:358672760476f2d4d6f6ff',
    messagingSenderId: '808393767406',
    projectId: 'login-7f7e4',
    databaseURL: 'https://login-7f7e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-7f7e4.appspot.com',
    androidClientId: '808393767406-keqkd75pra8lbp033237g5ajpti9f299.apps.googleusercontent.com',
    iosClientId: '808393767406-mainblgv6mii965ptlen326c8t16f1bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4a9NXP7VE0RzjQzmPv9SL8kSTNFbYAmA',
    appId: '1:808393767406:ios:358672760476f2d4d6f6ff',
    messagingSenderId: '808393767406',
    projectId: 'login-7f7e4',
    databaseURL: 'https://login-7f7e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-7f7e4.appspot.com',
    androidClientId: '808393767406-keqkd75pra8lbp033237g5ajpti9f299.apps.googleusercontent.com',
    iosClientId: '808393767406-mainblgv6mii965ptlen326c8t16f1bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );
}
